version: "3.8"
services:
    laravel:
        container_name: laravel
        build:
          context: .
          dockerfile: Dockerfile
          target: php
          args:
              - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 80:80
        depends_on:
            - mysql
            - mongodb
            - redis
        restart: unless-stopped
    mysql:
        container_name: mysql
        image: mysql:8.0
        ports:
            -   3306:3306
        environment:
            - MYSQL_DATABASE=default
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - mysql_data:/var/lib/mysql
        restart: unless-stopped
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        restart: unless-stopped
    redis:
        container_name:  redis
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass  "secret"
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data
        restart: unless-stopped
volumes:
    mysql_data:
    mongodb_data:
    redis_data:
